In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_json('train_data.json')
df

,id,syllogism,validity,plausibility
0,50146f21-d265-4e3a-8d93-8165cdbe89a3,All cars are a type of vehicle. No animal is a...,False,True
1,dfafb4f6-4e1d-4cd5-aeb4-75d36aafdf1a,Nothing that is a soda is a juice. A portion o...,True,True
2,e30b1f83-a4c3-49cb-8aaf-5f64208c625b,Everything that is a planet is a celestial bod...,False,False
3,a30e07d5-0fb3-4097-9892-4b145b0c54f5,Every cat is an invisible creature. A number o...,True,False
4,5b8161b7-b1bf-4e16-a854-cd52cdce8a1b,There are no capital cities which are oceans. ...,True,True
...,...,...,...,...
955,6df0ab4c-8518-4efb-98d5-e1bd172b5a35,Some creatures that can fly are birds. It is t...,False,True
956,0db674a5-4391-43fd-8d40-b6ec2b6e77e3,Every single thing that is a hammer is a tool....,False,True
957,6650eef5-2045-4ee2-8fe1-a3036d54c6b6,No person who is a doctor is also a teacher. A...,True,True
958,452c2309-abd1-4cd9-9cd9-1e693ef85cf6,A creature that is a reptile is never a mammal...,True,False
959,5bb97f94-d046-4219-9893-3b1bc4778d0b,Everything that is a tree is a plant. Not a si...,False,False

In [5]:
df["syllogism"] = df["syllogism"].str.lower()
df

,id,syllogism,validity,plausibility
0,50146f21-d265-4e3a-8d93-8165cdbe89a3,all cars are a type of vehicle. no animal is a...,False,True
1,dfafb4f6-4e1d-4cd5-aeb4-75d36aafdf1a,nothing that is a soda is a juice. a portion o...,True,True
2,e30b1f83-a4c3-49cb-8aaf-5f64208c625b,everything that is a planet is a celestial bod...,False,False
3,a30e07d5-0fb3-4097-9892-4b145b0c54f5,every cat is an invisible creature. a number o...,True,False
4,5b8161b7-b1bf-4e16-a854-cd52cdce8a1b,there are no capital cities which are oceans. ...,True,True
...,...,...,...,...
955,6df0ab4c-8518-4efb-98d5-e1bd172b5a35,some creatures that can fly are birds. it is t...,False,True
956,0db674a5-4391-43fd-8d40-b6ec2b6e77e3,every single thing that is a hammer is a tool....,False,True
957,6650eef5-2045-4ee2-8fe1-a3036d54c6b6,no person who is a doctor is also a teacher. a...,True,True
958,452c2309-abd1-4cd9-9cd9-1e693ef85cf6,a creature that is a reptile is never a mammal...,True,False
959,5bb97f94-d046-4219-9893-3b1bc4778d0b,everything that is a tree is a plant. not a si...,False,False

In [6]:
import spacy
import nltk
sp = spacy.load('en_core_web_sm')
def remove_punct(text):
    doc = sp(text)
    tokens = []
    for token in doc:
        if token.is_punct:
            if token.text == "." or token.text == ";" or token.text == ":":
                tokens.append(token.text)
        else:
            tokens.append(token.text)
    return " ".join(tokens)
df["syllogism"] = df["syllogism"].astype('str').apply(remove_punct)
df

,id,syllogism,validity,plausibility
0,50146f21-d265-4e3a-8d93-8165cdbe89a3,all cars are a type of vehicle . no animal is ...,False,True
1,dfafb4f6-4e1d-4cd5-aeb4-75d36aafdf1a,nothing that is a soda is a juice . a portion ...,True,True
2,e30b1f83-a4c3-49cb-8aaf-5f64208c625b,everything that is a planet is a celestial bod...,False,False
3,a30e07d5-0fb3-4097-9892-4b145b0c54f5,every cat is an invisible creature . a number ...,True,False
4,5b8161b7-b1bf-4e16-a854-cd52cdce8a1b,there are no capital cities which are oceans ....,True,True
...,...,...,...,...
955,6df0ab4c-8518-4efb-98d5-e1bd172b5a35,some creatures that can fly are birds . it is ...,False,True
956,0db674a5-4391-43fd-8d40-b6ec2b6e77e3,every single thing that is a hammer is a tool ...,False,True
957,6650eef5-2045-4ee2-8fe1-a3036d54c6b6,no person who is a doctor is also a teacher . ...,True,True
958,452c2309-abd1-4cd9-9cd9-1e693ef85cf6,a creature that is a reptile is never a mammal...,True,False
959,5bb97f94-d046-4219-9893-3b1bc4778d0b,everything that is a tree is a plant . not a s...,False,False

In [7]:
splits = df["syllogism"].str.split(".", n=2, expand=True)
df[["premise1", "premise2", "conclusion"]] = splits
df

,id,syllogism,validity,plausibility,premise1,premise2,conclusion
0,50146f21-d265-4e3a-8d93-8165cdbe89a3,all cars are a type of vehicle . no animal is ...,False,True,all cars are a type of vehicle,no animal is a car,therefore no animal can be a vehicle .
1,dfafb4f6-4e1d-4cd5-aeb4-75d36aafdf1a,nothing that is a soda is a juice . a portion ...,True,True,nothing that is a soda is a juice,a portion of the things that are beverages ar...,the only logical conclusion is that some beve...
2,e30b1f83-a4c3-49cb-8aaf-5f64208c625b,everything that is a planet is a celestial bod...,False,False,everything that is a planet is a celestial body,anything that is a sun is a celestial body,there exists at least one sun that is a planet .
3,a30e07d5-0fb3-4097-9892-4b145b0c54f5,every cat is an invisible creature . a number ...,True,False,every cat is an invisible creature,a number of cats are animals,consequently a portion of animals are invisib...
4,5b8161b7-b1bf-4e16-a854-cd52cdce8a1b,there are no capital cities which are oceans ....,True,True,there are no capital cities which are oceans,a select few large cities are classified as c...,therefore it is clear that some large cities ...
...,...,...,...,...,...,...,...
955,6df0ab4c-8518-4efb-98d5-e1bd172b5a35,some creatures that can fly are birds . it is ...,False,True,some creatures that can fly are birds,it is true that some sparrows are flying crea...,for this reason every single sparrow is a bird .
956,0db674a5-4391-43fd-8d40-b6ec2b6e77e3,every single thing that is a hammer is a tool ...,False,True,every single thing that is a hammer is a tool,all screwdrivers are also tools,it must be true that no screwdriver is a hamm...
957,6650eef5-2045-4ee2-8fe1-a3036d54c6b6,no person who is a doctor is also a teacher . ...,True,True,no person who is a doctor is also a teacher,anything that is a teacher is a profession,therefore some professions are not doctors .
958,452c2309-abd1-4cd9-9cd9-1e693ef85cf6,a creature that is a reptile is never a mammal...,True,False,a creature that is a reptile is never a mammal,there is a group of reptiles that are also el...,it must logically follow that some elephants ...
959,5bb97f94-d046-4219-9893-3b1bc4778d0b,everything that is a tree is a plant . not a s...,False,False,everything that is a tree is a plant,not a single human is a plant,all humans are trees .

In [8]:
import spacy

nlp = spacy.load("en_core_web_sm")


# -------------------------
# Utility: resolve "type of X"
# -------------------------
def resolve_predicate(token):
    for child in token.children:
        if child.dep_ == "prep" and child.lemma_ == "of":
            for grand in child.children:
                if grand.dep_ == "pobj":
                    return grand
    return token


# -------------------------
# Utility: extract nouns safely
# -------------------------
def extract_nouns(doc):
    return [t.lemma_ for t in doc if t.pos_ == "NOUN"]


# -------------------------
# MAIN LOGIC EXTRACTOR (NEVER RETURNS NONE)
# -------------------------
def extract_logic(sentence):
    doc = nlp(sentence)

    quantifier = None
    subject = None
    predicate = None
    negated = False

    # ---------- EXISTENTIAL ----------
    for token in doc:
        if token.lemma_ == "exist":
            quantifier = "I"
            nouns = extract_nouns(doc)
            if len(nouns) >= 2:
                return ("I", nouns[0], nouns[1])
            elif len(nouns) == 1:
                return ("I", nouns[0], nouns[0])

    # ---------- COPULAR ----------
    copula = None
    for token in doc:
        if token.dep_ == "ROOT" and token.lemma_ == "be":
            copula = token
            break

    if copula:
        # subject
        for child in copula.children:
            if child.dep_ == "nsubj":
                subject = child
                break

        # predicate
        for child in copula.children:
            if child.dep_ in {"attr", "acomp"}:
                predicate = resolve_predicate(child)
                break

        # quantifier
        if subject:
            for child in subject.children:
                if child.dep_ == "det":
                    if child.lemma_ in {"all", "every", "each"}:
                        quantifier = "A"
                    elif child.lemma_ == "no":
                        quantifier = "E"
                    elif child.lemma_ in {"some", "a", "an"}:
                        quantifier = "I"

        # negation
        for child in copula.children:
            if child.dep_ == "neg":
                negated = True

        if quantifier == "A" and negated:
            quantifier = "O"
        if quantifier == "I" and negated:
            quantifier = "O"

        if quantifier and subject and predicate:
            return (quantifier, subject.lemma_, predicate.lemma_)

    # ---------- FALLBACK (GUARANTEED) ----------
    nouns = extract_nouns(doc)

    if len(nouns) >= 2:
        return ("I", nouns[0], nouns[1])
    elif len(nouns) == 1:
        return ("I", nouns[0], nouns[0])
    else:
        return ("I", "thing", "thing")



df["logical_expression_1"] = df["premise1"].apply(extract_logic)
df["logical_expression_2"] = df["premise2"].apply(extract_logic)
df["logical_expression_3"] = df["conclusion"].apply(extract_logic)
df

,id,syllogism,validity,plausibility,premise1,premise2,conclusion,logical_expression_1,logical_expression_2,logical_expression_3
0,50146f21-d265-4e3a-8d93-8165cdbe89a3,all cars are a type of vehicle . no animal is ...,False,True,all cars are a type of vehicle,no animal is a car,therefore no animal can be a vehicle .,"(A, car, vehicle)","(E, animal, car)","(E, animal, vehicle)"
1,dfafb4f6-4e1d-4cd5-aeb4-75d36aafdf1a,nothing that is a soda is a juice . a portion ...,True,True,nothing that is a soda is a juice,a portion of the things that are beverages ar...,the only logical conclusion is that some beve...,"(I, soda, juice)","(I, portion, juice)","(I, conclusion, beverage)"
2,e30b1f83-a4c3-49cb-8aaf-5f64208c625b,everything that is a planet is a celestial bod...,False,False,everything that is a planet is a celestial body,anything that is a sun is a celestial body,there exists at least one sun that is a planet .,"(I, planet, body)","(I, sun, body)","(I, sun, planet)"
3,a30e07d5-0fb3-4097-9892-4b145b0c54f5,every cat is an invisible creature . a number ...,True,False,every cat is an invisible creature,a number of cats are animals,consequently a portion of animals are invisib...,"(A, cat, creature)","(I, number, animal)","(I, portion, invisible)"
4,5b8161b7-b1bf-4e16-a854-cd52cdce8a1b,there are no capital cities which are oceans ....,True,True,there are no capital cities which are oceans,a select few large cities are classified as c...,therefore it is clear that some large cities ...,"(I, capital, city)","(I, city, capital)","(I, city, ocean)"
...,...,...,...,...,...,...,...,...,...,...
955,6df0ab4c-8518-4efb-98d5-e1bd172b5a35,some creatures that can fly are birds . it is ...,False,True,some creatures that can fly are birds,it is true that some sparrows are flying crea...,for this reason every single sparrow is a bird .,"(I, creature, bird)","(I, sparrow, creature)","(A, sparrow, bird)"
956,0db674a5-4391-43fd-8d40-b6ec2b6e77e3,every single thing that is a hammer is a tool ...,False,True,every single thing that is a hammer is a tool,all screwdrivers are also tools,it must be true that no screwdriver is a hamm...,"(A, thing, tool)","(A, screwdriver, tool)","(I, screwdriver, hammer)"
957,6650eef5-2045-4ee2-8fe1-a3036d54c6b6,no person who is a doctor is also a teacher . ...,True,True,no person who is a doctor is also a teacher,anything that is a teacher is a profession,therefore some professions are not doctors .,"(E, person, teacher)","(I, teacher, profession)","(O, profession, doctor)"
958,452c2309-abd1-4cd9-9cd9-1e693ef85cf6,a creature that is a reptile is never a mammal...,True,False,a creature that is a reptile is never a mammal,there is a group of reptiles that are also el...,it must logically follow that some elephants ...,"(O, creature, mammal)","(I, group, reptile)","(I, elephant, mammal)"
959,5bb97f94-d046-4219-9893-3b1bc4778d0b,everything that is a tree is a plant . not a s...,False,False,everything that is a tree is a plant,not a single human is a plant,all humans are trees .,"(I, tree, plant)","(I, human, plant)","(A, human, tree)"

In [9]:
import spacy

# -----------------------------
# Load NLP
# -----------------------------
nlp = spacy.load("en_core_web_sm")

# -----------------------------
# 19 Valid Syllogisms
# -----------------------------
VALID_SYLLOGISMS = {
    1: {"AAA", "EAE", "AII", "EIO"},
    2: {"EAE", "AEE", "EIO", "AOO"},
    3: {"AAI", "IAI", "AII", "EAO", "OAO", "EIO"},
    4: {"AAI", "AEE", "IAI", "EAO", "EIO"},
}

# -----------------------------
# Utilities
# -----------------------------
def resolve_predicate(token):
    """Resolve 'type/kind of X' → X."""
    for c in token.children:
        if c.dep_ == "prep" and c.lemma_ == "of":
            for g in c.children:
                if g.dep_ == "pobj":
                    return g
    return token

def extract_nouns(doc):
    return [t.lemma_ for t in doc if t.pos_ == "NOUN"]

def is_existential(doc):
    return any(t.lemma_ in {"exist"} for t in doc) or \
           any(t.lemma_ == "there" for t in doc)

# -----------------------------
# Logic Extractor (NEVER None)
# -----------------------------
def extract_logic(sentence):
    doc = nlp(sentence)

    # --- Existential cases ---
    if is_existential(doc):
        nouns = extract_nouns(doc)
        if len(nouns) >= 2:
            return ("I", nouns[0], nouns[1])
        elif len(nouns) == 1:
            return ("I", nouns[0], nouns[0])
        else:
            return ("I", "thing", "thing")

    # --- Copular cases ---
    copula = None
    for t in doc:
        if t.dep_ == "ROOT" and t.lemma_ == "be":
            copula = t
            break

    if copula:
        subject = None
        predicate = None
        quantifier = None
        negated = False

        # subject
        for c in copula.children:
            if c.dep_ == "nsubj":
                subject = c
                break

        # predicate
        for c in copula.children:
            if c.dep_ in {"attr", "acomp"}:
                predicate = resolve_predicate(c)
                break

        # quantifier
        if subject:
            for c in subject.children:
                if c.dep_ == "det":
                    if c.lemma_ in {"all", "every", "each"}:
                        quantifier = "A"
                    elif c.lemma_ == "no":
                        quantifier = "E"
                    elif c.lemma_ in {"some", "a", "an"}:
                        quantifier = "I"

        # negation
        for c in copula.children:
            if c.dep_ == "neg":
                negated = True

        if quantifier == "A" and negated:
            quantifier = "O"
        if quantifier == "I" and negated:
            quantifier = "O"

        if quantifier and subject and predicate:
            return (quantifier, subject.lemma_, predicate.lemma_)

    # --- Fallback (guaranteed) ---
    nouns = extract_nouns(doc)
    if len(nouns) >= 2:
        return ("I", nouns[0], nouns[1])
    elif len(nouns) == 1:
        return ("I", nouns[0], nouns[0])
    else:
        return ("I", "thing", "thing")

# -----------------------------
# S, P, M identification
# -----------------------------
def identify_terms(p1, p2, concl):
    _, s1, p1_ = p1
    _, s2, p2_ = p2
    _, s3, p3_ = concl

    S = s3
    P = p3_
    premise_terms = {s1, p1_, s2, p2_}
    candidates = premise_terms - {S, P}
    if len(candidates) != 1:
        return None
    M = candidates.pop()
    return {"S": S, "P": P, "M": M}

# -----------------------------
# Figure detection
# -----------------------------
def determine_figure(p1, p2, terms):
    _, s1, p1_ = p1
    _, s2, p2_ = p2
    S, M = terms["S"], terms["M"]

    def form(s, p):
        return ("M" if s == M else "P", "M" if p == M else "P")

    p1f = form(s1, p1_)
    p2f = ("S" if s2 == S else "M", "M" if p2_ == M else "P")

    if p1f == ("M", "P") and p2f == ("S", "M"): return 1
    if p1f == ("P", "M") and p2f == ("S", "M"): return 2
    if p1f == ("M", "P") and p2f == ("M", "S"): return 3
    if p1f == ("P", "M") and p2f == ("M", "S"): return 4
    return None

def extract_mood(p1, p2, concl):
    return p1[0] + p2[0] + concl[0]

# -----------------------------
# Validity Predictor (THE MODEL)
# -----------------------------
def predict_validity(p1, p2, concl):
    terms = identify_terms(p1, p2, concl)
    if terms is None:
        return False
    figure = determine_figure(p1, p2, terms)
    if figure is None:
        return False
    mood = extract_mood(p1, p2, concl)
    return mood in VALID_SYLLOGISMS.get(figure, set())

# -----------------------------
# Apply to DataFrame
# -----------------------------
# Assumes columns: premise1, premise2, conclusion
# Produces: logical_expression_1/2/3 and predicted_validity

def run_pipeline(df):
    df = df.copy()
    df["logical_expression_1"] = df["premise1"].apply(extract_logic)
    df["logical_expression_2"] = df["premise2"].apply(extract_logic)
    df["logical_expression_3"] = df["conclusion"].apply(extract_logic)

    df["predicted_validity"] = df.apply(
        lambda r: predict_validity(
            r["logical_expression_1"],
            r["logical_expression_2"],
            r["logical_expression_3"]
        ),
        axis=1
    )
    return df

In [10]:
df = run_pipeline(df)
df

,id,syllogism,validity,plausibility,premise1,premise2,conclusion,logical_expression_1,logical_expression_2,logical_expression_3,predicted_validity
0,50146f21-d265-4e3a-8d93-8165cdbe89a3,all cars are a type of vehicle . no animal is ...,False,True,all cars are a type of vehicle,no animal is a car,therefore no animal can be a vehicle .,"(A, car, vehicle)","(E, animal, car)","(E, animal, vehicle)",False
1,dfafb4f6-4e1d-4cd5-aeb4-75d36aafdf1a,nothing that is a soda is a juice . a portion ...,True,True,nothing that is a soda is a juice,a portion of the things that are beverages ar...,the only logical conclusion is that some beve...,"(I, soda, juice)","(I, portion, juice)","(I, conclusion, beverage)",False
2,e30b1f83-a4c3-49cb-8aaf-5f64208c625b,everything that is a planet is a celestial bod...,False,False,everything that is a planet is a celestial body,anything that is a sun is a celestial body,there exists at least one sun that is a planet .,"(I, planet, body)","(I, sun, body)","(I, sun, planet)",False
3,a30e07d5-0fb3-4097-9892-4b145b0c54f5,every cat is an invisible creature . a number ...,True,False,every cat is an invisible creature,a number of cats are animals,consequently a portion of animals are invisib...,"(A, cat, creature)","(I, number, animal)","(I, portion, invisible)",False
4,5b8161b7-b1bf-4e16-a854-cd52cdce8a1b,there are no capital cities which are oceans ....,True,True,there are no capital cities which are oceans,a select few large cities are classified as c...,therefore it is clear that some large cities ...,"(I, capital, city)","(I, city, capital)","(I, city, ocean)",False
...,...,...,...,...,...,...,...,...,...,...,...
955,6df0ab4c-8518-4efb-98d5-e1bd172b5a35,some creatures that can fly are birds . it is ...,False,True,some creatures that can fly are birds,it is true that some sparrows are flying crea...,for this reason every single sparrow is a bird .,"(I, creature, bird)","(I, sparrow, creature)","(A, sparrow, bird)",False
956,0db674a5-4391-43fd-8d40-b6ec2b6e77e3,every single thing that is a hammer is a tool ...,False,True,every single thing that is a hammer is a tool,all screwdrivers are also tools,it must be true that no screwdriver is a hamm...,"(A, thing, tool)","(A, screwdriver, tool)","(I, screwdriver, hammer)",False
957,6650eef5-2045-4ee2-8fe1-a3036d54c6b6,no person who is a doctor is also a teacher . ...,True,True,no person who is a doctor is also a teacher,anything that is a teacher is a profession,therefore some professions are not doctors .,"(E, person, teacher)","(I, teacher, profession)","(O, profession, doctor)",False
958,452c2309-abd1-4cd9-9cd9-1e693ef85cf6,a creature that is a reptile is never a mammal...,True,False,a creature that is a reptile is never a mammal,there is a group of reptiles that are also el...,it must logically follow that some elephants ...,"(O, creature, mammal)","(I, group, reptile)","(I, elephant, mammal)",False
959,5bb97f94-d046-4219-9893-3b1bc4778d0b,everything that is a tree is a plant . not a s...,False,False,everything that is a tree is a plant,not a single human is a plant,all humans are trees .,"(I, tree, plant)","(I, human, plant)","(A, human, tree)",False

In [11]:
df[df["predicted_validity"] == True].shape[0]

8

In [12]:
(df["validity"] == df["predicted_validity"]).sum() / len(df)

np.float64(0.49375)

In [13]:
df_train_data = df_train_data = pd.concat([df["premise1"], df["premise2"], df["conclusion"]], axis=0, ignore_index=True)
df_train_data

0                         all cars are a type of vehicle
1                      nothing that is a soda is a juice
2        everything that is a planet is a celestial body
3                     every cat is an invisible creature
4           there are no capital cities which are oceans
                              ...
2875     for this reason every single sparrow is a bird .
2876     it must be true that no screwdriver is a hamm...
2877         therefore some professions are not doctors .
2878     it must logically follow that some elephants ...
2879                               all humans are trees .
Length: 2880, dtype: object

In [14]:
df_train_data.to_csv('training.csv')

In [31]:
df_out = pd.read_csv("output.csv", sep = " ", header = None)
df_out

       0  1             2                   3
0      1  E          soda               juice
1      2  A        planet      celestial_body
2      3  A           cat  invisible_creature
3      4  E  capital_city               ocean
4      5  A          city            location
..   ... ..           ...                 ...
993  994  E      building              animal
994  995  A          bird                 dog
995  996  E     structure               cloud
996  997  A         house            building
997  998  A        animal           retriever

[998 rows x 4 columns]

In [32]:
df_out.drop(df_out.columns[0], axis = 1, inplace=True)
df_out

     1             2                   3
0    E          soda               juice
1    A        planet      celestial_body
2    A           cat  invisible_creature
3    E  capital_city               ocean
4    A          city            location
..  ..           ...                 ...
993  E      building              animal
994  A          bird                 dog
995  E     structure               cloud
996  A         house            building
997  A        animal           retriever

[998 rows x 3 columns]

In [35]:
df_m = pd.concat([df_train_data, df_out], axis=1)
df_m

,0,1,2,3
0,all cars are a type of vehicle,E,soda,juice
1,nothing that is a soda is a juice,A,planet,celestial_body
2,everything that is a planet is a celestial body,A,cat,invisible_creature
3,every cat is an invisible creature,E,capital_city,ocean
4,there are no capital cities which are oceans,A,city,location
...,...,...,...,...
2875,for this reason every single sparrow is a bird .,NaN,NaN,NaN
2876,it must be true that no screwdriver is a hamm...,NaN,NaN,NaN
2877,therefore some professions are not doctors .,NaN,NaN,NaN
2878,it must logically follow that some elephants ...,NaN,NaN,NaN
2879,all humans are trees .,NaN,NaN,NaN

In [36]:
df_m.to_csv('training1.csv', index=False)