In [31]:
import pandas as pd
df = pd.read_csv('training.csv', header=None)
df

         0                                                  1
0        0                    all cars are a type of vehicle
1        1                 nothing that is a soda is a juice
2        2   everything that is a planet is a celestial body
3        3                every cat is an invisible creature
4        4      there are no capital cities which are oceans
...    ...                                                ...
2875  2875   for this reason every single sparrow is a bird .
2876  2876   it must be true that no screwdriver is a hamm...
2877  2877       therefore some professions are not doctors .
2878  2878   it must logically follow that some elephants ...
2879  2879                             all humans are trees .

[2880 rows x 2 columns]

In [33]:
df = df.rename(columns={0 : "id", 1 : "premise"})
df

        id                                            premise
0        0                    all cars are a type of vehicle
1        1                 nothing that is a soda is a juice
2        2   everything that is a planet is a celestial body
3        3                every cat is an invisible creature
4        4      there are no capital cities which are oceans
...    ...                                                ...
2875  2875   for this reason every single sparrow is a bird .
2876  2876   it must be true that no screwdriver is a hamm...
2877  2877       therefore some professions are not doctors .
2878  2878   it must logically follow that some elephants ...
2879  2879                             all humans are trees .

[2880 rows x 2 columns]

In [36]:
df = df.drop(df.columns[0], axis=1)
df

                                                premise
0                       all cars are a type of vehicle
1                    nothing that is a soda is a juice
2      everything that is a planet is a celestial body
3                   every cat is an invisible creature
4         there are no capital cities which are oceans
...                                                 ...
2875   for this reason every single sparrow is a bird .
2876   it must be true that no screwdriver is a hamm...
2877       therefore some professions are not doctors .
2878   it must logically follow that some elephants ...
2879                             all humans are trees .

[2880 rows x 1 columns]

In [43]:
df_1 = pd.read_csv('actual_training.csv', sep=" ", header=None)
df_1

      0          1           2
0     A        car     vehicle
1     E       soda       juice
2     A     planet        body
3     A        cat    creature
4     E       city       ocean
...  ..        ...         ...
5163  E      snake     reptile
5164  I      shape      circle
5165  A     london        city
5166  I  retriever         dog
5167  E  arthropod  vertebrate

[5168 rows x 3 columns]

In [44]:
df_1 = df_1.rename(columns={0:"type", 1:"noun1", 2:"noun2"})
df_1["canonical_form"] = (df_1["type"] + " " + df_1["noun1"] + " " + df_1["noun2"])
df_1

     type      noun1       noun2          canonical_form
0       A        car     vehicle           A car vehicle
1       E       soda       juice            E soda juice
2       A     planet        body           A planet body
3       A        cat    creature          A cat creature
4       E       city       ocean            E city ocean
...   ...        ...         ...                     ...
5163    E      snake     reptile         E snake reptile
5164    I      shape      circle          I shape circle
5165    A     london        city           A london city
5166    I  retriever         dog         I retriever dog
5167    E  arthropod  vertebrate  E arthropod vertebrate

[5168 rows x 4 columns]

In [45]:
df_1 = df_1.drop(df_1.columns[[0, 1, 2]], axis = 1)
df_1

              canonical_form
0              A car vehicle
1               E soda juice
2              A planet body
3             A cat creature
4               E city ocean
...                      ...
5163         E snake reptile
5164          I shape circle
5165           A london city
5166         I retriever dog
5167  E arthropod vertebrate

[5168 rows x 1 columns]

In [46]:
df_train = pd.DataFrame(columns=["premise", "canonical_form"])

for i, row1 in df.iterrows():
    premise = row1["premise"]  
    for m, row2 in df_1.iterrows():
        canonical = row2["canonical_form"]
        c = canonical.split(" ")  
        if len(c) >= 3 and c[1] in premise and c[2] in premise:
            new_row = pd.DataFrame({"premise": [premise],"canonical_form": [canonical]})
            df_train = pd.concat([df_train, new_row], ignore_index=True)
            break  

df_train

                                                premise     canonical_form
0                       all cars are a type of vehicle       A car vehicle
1                    nothing that is a soda is a juice        E soda juice
2      everything that is a planet is a celestial body       A planet body
3                   every cat is an invisible creature      A cat creature
4         there are no capital cities which are oceans       E ocean ocean
...                                                 ...                ...
2475   it can be deduced that some water is not liqu...     O water liquid
2476   therefore it is argued that there are no dogs...       O dog animal
2477   for this reason every single sparrow is a bird .     A sparrow bird
2478   it must logically follow that some elephants ...  I elephant mammal
2479                             all humans are trees .       E human tree

[2480 rows x 2 columns]

In [47]:
df_train.rename(columns={"premise" : "input", "canonical_form" : "output"}, inplace=True)
df_train.to_json("training_t5.jsonl", orient="records", lines=True)